apiVersion: v1
kind: Namespace
metadata:
  name: warehouse-staging
  labels:
    name: warehouse-staging
---
apiVersion: v1
kind: Namespace
metadata:
  name: warehouse-production
  labels:
    name: warehouse-production
