apiVersion: v1
kind: Secret
metadata:
  name: warehouse-db-secret-staging
  namespace: warehouse-staging
type: Opaque
data:
  jdbc-url: amRiYzpwb3N0Z3Jlc3FsOi8vcG9zdGdyZXMtc2VydmljZTo1NDMyL3dhcmVob3VzZV9zdGFnaW5n  # Base64 encoded
  username: d2FyZWhvdXNl  # Base64 encoded
  password: d2FyZWhvdXNlMTIz  # Base64 encoded
---
apiVersion: v1
kind: Secret
metadata:
  name: warehouse-db-secret-production
  namespace: warehouse-production
type: Opaque
data:
  jdbc-url: amRiYzpwb3N0Z3Jlc3FsOi8vcG9zdGdyZXMtc2VydmljZTo1NDMyL3dhcmVob3VzZQ==  # Base64 encoded
  username: d2FyZWhvdXNl  # Base64 encoded
  password: d2FyZWhvdXNlMTIz  # Base64 encoded
